### ISSUE TITLE
build issue..

### ISSUE THREAD

**Issue by ntechnix** [xogium/buildroot-stm32mp135d-odyssey#1]
I tested stm32mp135d-odyssey boad use this.

use sd boot option but board is issue found.
boot issue is....

NOTICE:  CPU: STM32MP135D Rev.Y
NOTICE:  Model: Seeed STM32MP135D Odyssey Board
ERROR:   Boot interface 1 not supported
PANIC at PC : 0x2ffe7647

**Comment by xogium** [comment]
Hi @namix71. I will fix this. I hadn't noticed that the tf-a build was missing the sdmmc interface. I will fix this and make r3 release. This should be available in about 5 minutes max.

Thank you for reporting this, really appreciated. And sorry for the slight oversight!

**Comment by xogium** [comment]
Oops sorry, not r3 release for tf-a but just fixing the buildroot build. I will eventually make tagged releases for this repo also, btw

Don't hesitate if you find other problems btw.

**Comment by ntechnix** [comment]
Thank you for your quick response. 
I will test it later and give you feedback.

**Comment by xogium** [comment]
You should be able to rebuild again in the following ways:
* make menuconfig, bootloaders menu then modify the additional arm-trusted-firmware variables to add the STM32MP_SDMMC=1 variable
* or make distclean followed by make BR2_EXTERNAL=... again

**Comment by ntechnix** [comment]
Okay. I will it.
Thank  you..

**Comment by xogium** [comment]
Sure thing. If you have still a problem I will reopen and we'll dig more into it. I don't have a micro sd to test on this board, my bad for the missing option! Fingers crossed that it fixes it.
